#!/bin/bash
#########################################
#########################################
###          SCRIPT veianew_PDV       ###
###          DATE 20/09/2019          ###
#########################################
#############MCARVALHO###################
#############RAZARIAS####################
VERSION="v2.4.1"
export LANG=pt_BR

# rsantos INICIO
# umount /Zanthus/Zeus/path_comum/

${Z_MOUNT}

O1S="/tmp/0.15"
if [ -d "${O1S}" ] ; then
umount "${O1S}"
else
mkdir "${O1S}" & chmod 777 "${O1S}"
fi

export moduloPHPPDV="/Zanthus/Zeus/path_comum/moduloPHPPDV"
if [ -d "${moduloPHPPDV}" ] ; then
umount "${moduloPHPPDV}"
else
mkdir "${moduloPHPPDV}" & chmod 777 "${moduloPHPPDV}" &
fi

Scripts_veianew="/tmp/0.15/Scripts_veianew"
if [ -d "${Scripts_veianew}" ] ; then
umount "${Scripts_veianew}"
else
mkdir "${Scripts_veianew}" & chmod 777 "${Scripts_veianew}" &
fi

Path_Comum="/Zanthus/Zeus/path_comum"
if [ -d "${Path_Comum}" ] ; then
umount "${Path_Comum}"
else
mkdir "${Path_Comum}" & chmod 777 "${Path_Comum}" &
fi


dirRoot="/bin"
veianewpdvIni="${dirRoot}/veianewpdv.ini"
atualizaSenha(){
  echo "INFORME SEU USUARIO E SENHA DE ACESSO AO '192.168.0.15'"
  echo -ne "USUARIO: "
  read USUARIO_15
  echo -ne "SENHA: "
  read SENHA_15
  echo "USUARIO_15=${USUARIO_15}" >  ${veianewpdvIni}
  echo "SENHA_15=${SENHA_15}"     >> ${veianewpdvIni}
}
montar15(){
  SERVIDOR1='192.168.0.15/zanthusinterno/Public/qualidade/VERSOES/Manager'
  COMANDO1="mount -t cifs -s -o username=$USUARIO_15,password=$SENHA_15,rw,sec=ntlm //$SERVIDOR1 $manager"
  #$COMANDO1

  SERVIDOR2='192.168.0.15/zanthusinterno/Public/qualidade/VERSOES/moduloPHPPDV'
  COMANDO2="mount -t cifs -s -o username=$USUARIO_15,password=$SENHA_15,rw,sec=ntlm //$SERVIDOR2 $moduloPHPPDV"
  ${COMANDO2}

  SERVIDOR3='192.168.0.15/zanthusinterno/Public/qualidade/VERSOES/Scripts_veianew'
  COMANDO3="mount -t cifs -s -o username=$USUARIO_15,password=$SENHA_15,rw,sec=ntlm //$SERVIDOR3 $Scripts_veianew"

  return $?
}
if [ -e "${veianewpdvIni}" ]
then
 . ${veianewpdvIni}
else
  atualizaSenha
fi
montar15
if [ ${?} -ne "0" ]
then
  OPC=0
  while [ ${OPC} -ne 1 -a ${OPC} -ne 2 ]
  do
    echo -e  "NÃO FOI POSSIVEL MONTAR O CAMINHO //$SERVIDOR UTILIZANDO O COMANDO ABAIXO\n ($COMANDO)"
    echo     "O QUE VOCE DESEJA FAZER?"
    echo     "1. PROSSEGUIR SEM MONTAR (utilizar versoes copiadas anteriormente)"
    echo     "2. ATUALIZAR USUARIO E SENHA DE ACESSO AO '192.168.0.15'"
    echo -ne "OPCAO: "
    read     OPC
    case ${OPC} in
      1)
        echo "PROSSEGUINDO ..."
      ;;
      2)
        atualizaSenha
        montar15
        [ $? -ne 0 ] && OPC=0
      ;;
      *)
        echo "DIGITE UMA OPCAO VALIDA!"
      ;;
    esac
  done
fi
# rsantos FIM

${COMANDO3}
IP=`ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
echo -e "$HOSTNAME" "   -   " "$IP" "   -   " "$(date +%d/%m/%y__%H:%M:%S)" "   -   " "$VERSION" >> ${Scripts_veianew}/LOGVN/${HOSTNAME}.VNL;

umount ${Scripts_veianew}

rsync -uvt /tmp/0.15/*.zip ${moduloPHPPDV}

sleep 1 && umount /tmp/0.15

cd ${moduloPHPPDV}
echo "mostrando pwd"

for arquivo in *.ZIP
do
newname=$(basename ${arquivo} ZIP)zip
mv ${arquivo} ${newname}
done

cd ${moduloPHPPDV}

chown root.root ${moduloPHPPDV}/*
chmod 777 ${moduloPHPPDV}/*.zip

for file in *odulo*.zip

do
   if [ ! "$file" = `echo "$file"|sed "s/ /_/g"` ]; then
   mv "$file" `echo "$file"|sed "s/ /_/g"`
   fi
# echo $file
done

find . -name "*odulo*.zip"

ListaArquivos(){
if [ `find . -name '*anager*.zip' | wc -l` -gt 0 ]; then
clear; i=1

echo -e "#     \033[1;1;33mOPÇÕES\t\b\b***********************  PACOTES MODULOPHPPDV  ***********************\033[0m"
CASE='case $opt in'
for arq in `ls -1tr *odulo*.zip`
do
    echo -e "#\t\b\b\b\b$i    $arq"
    CASE="${CASE}
   $i) cd /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/; service zanthus stop; rm -rf *.zip.TEMP; rsync -uv "${moduloPHPPDV}/\"$arq\"" /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/; unzip -oq \"$arq\"; touch \"$arq.TEMP\"; sleep 3; service zanthus start;  echo -e '#\tEXTRACAO CONCLUIDA' ;;"
    i=$((i+1))
done
CASE="${CASE}
   99) rm -rf /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/* ; sleep 1 && veianewpdv ;;

   89) service zanthus start ; sleep 1 && veianewpdv ;;
   88) service zanthus stop ; sleep 1 && veianewpdv ;;

   79) echo -e '***** Montando Path_comum*****'; ${Z_MOUNT};  rsync -uv /Zanthus/Zeus/path_comum/so/* /Zanthus/Zeus/lib; if [ "$?" -eq "0" ]; then echo -e '***** Bibliotecas atualizadas com Sucesso LIB *****'; fi;  rsync -uv /Zanthus/Zeus/path_comum/so_co5/* /Zanthus/Zeus/lib_co5 ; if [ "$?" -eq "0" ]; then echo -e '***** Bibliotecas atualizadas com Sucesso LIB_CO5 *****'; fi;  rsync -uv /Zanthus/Zeus/path_comum/so_ubu/* /Zanthus/Zeus/lib_ubu; if [ "$?" -eq "0" ]; then echo -e '***** Bibliotecas atualizadas com Sucesso LIB_UBU *****'; fi;  echo -e '***** Executando ldconfig*****'; ldconfig ; sleep 1 && veianewpdv ;;
   78) dpkg-reconfigure tzdata ; sleep 1 && veianewpdv ;;
   77) ${Z_MOUNT} ; echo -e 'Aguarde, conectando no ftp.zanthus.com.br';  echo -e 'Atualizando bibliotecas para o PATH_COMUM!!!'; sleep 3 && wget -N -v --tries=2 -P ${Path_Comum}/so/ ftp://200.201.215.247:2142/pub/Zeus_Frente_de_Loja/_Complementares/so/* ; wget -N -v --tries=2 -P ${Path_Comum}/so_co5 ftp://200.201.215.247:2142/pub/Zeus_Frente_de_Loja/_Complementares/so_co5/* ; wget -N -v --tries=2 -P ${Path_Comum}/so_r64 ftp://200.201.215.247:2142/pub/Zeus_Frente_de_Loja/_Complementares/so_r64/* ; wget -N -v --tries=2 -P ${Path_Comum}/so_u64 ftp://200.201.215.247:2142/pub/Zeus_Frente_de_Loja/_Complementares/so_u64/* ; wget -N -v --tries=2 -P ${Path_Comum}/so_ubu ftp://200.201.215.247:2142/pub/Zeus_Frente_de_Loja/_Complementares/so_ubu/* ; sleep 1 && veianewpdv ;;

   59) ${COMANDO2}; sleep 3; cp -rf ${moduloPHPPDV}/sat_lab_bematec.conf   /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/sat_lab.conf; sleep 3 ; umount ${moduloPHPPDV}; sleep 1 && veianewpdv ;;
   58) ${COMANDO2}; sleep 3; cp -rf ${moduloPHPPDV}/sat_lab_dimep.conf     /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/sat_lab.conf; sleep 3 ; umount ${moduloPHPPDV}; sleep 1 && veianewpdv ;;
   57) ${COMANDO2}; sleep 3; cp -rf ${moduloPHPPDV}/sat_lab_elgin.conf     /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/sat_lab.conf; sleep 3 ; umount ${moduloPHPPDV}; sleep 1 && veianewpdv ;;
   56) ${COMANDO2}; sleep 3; cp -rf ${moduloPHPPDV}/sat_lab_gertec.conf    /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/sat_lab.conf; sleep 3 ; umount ${moduloPHPPDV}; sleep 1 && veianewpdv ;;
   55) ${COMANDO2}; sleep 3; cp -rf ${moduloPHPPDV}/sat_lab_kryptus.conf   /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/sat_lab.conf; sleep 3 ; umount ${moduloPHPPDV}; sleep 1 && veianewpdv ;;
   54) ${COMANDO2}; sleep 3; cp -rf ${moduloPHPPDV}/sat_lab_mfe_tanca.conf /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/sat_lab.conf; sleep 3 ; umount ${moduloPHPPDV}; sleep 1 && veianewpdv ;;
   53) ${COMANDO2}; sleep 3; cp -rf ${moduloPHPPDV}/sat_lab_nitere.conf    /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/sat_lab.conf; sleep 3 ; umount ${moduloPHPPDV}; sleep 1 && veianewpdv ;;
   52) ${COMANDO2}; sleep 3; cp -rf ${moduloPHPPDV}/sat_lab_sweda.conf     /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/sat_lab.conf; sleep 3 ; umount ${moduloPHPPDV}; sleep 1 && veianewpdv ;;
   51) ${COMANDO2}; sleep 3; cp -rf ${moduloPHPPDV}/sat_lab_tanca.conf     /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/sat_lab.conf; sleep 3 ; umount ${moduloPHPPDV}; sleep 1 && veianewpdv ;;
   50) ${COMANDO2}; sleep 3; cp -rf ${moduloPHPPDV}/sat_lab_urano.conf     /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/sat_lab.conf; sleep 3 ; umount ${moduloPHPPDV}; sleep 1 && veianewpdv ;;

   01) rm -rf /bin/veianewpdv_OLD ; cp /bin/veianewpdv /bin/veianewpdv_OLD ; ${COMANDO3} ; sleep 3 ; rsync -uv /tmp/0.15/Scripts_veianew/veianewpdv_ATUALIZADO /bin/veianewpdv_ATUALIZADO && umount /tmp/0.15/Scripts_veianew/ ; mv /bin/veianewpdv_ATUALIZADO /bin/veianewpdv ; sleep 1 ; echo -e ""; echo -e ""; echo -e 'Atualizacao do veianewpdv concluida com sucesso!!!'; echo -e ""; echo -e "" ;;
   00) exit ;;
    *) echo 'OPCAO INVALIDA! TENTE NOVAMENTE'; sleep 2; clear; ListaArquivos ;;
esac"

cd /Zanthus/Zeus/pdvJava/GERAL/SINCRO/WEB/moduloPHPPDV/

echo -e ""
echo -e ""
echo -e "#\t\033[1;33m\b\b\b\bMODULO EM USO:" *.zip.TEMP
echo -e "\033[0;0m"
echo -e "#\t\b\b\b\b99    LIMPAR DIRETORIO MODULOPHPPDV"
echo -e ""
echo -e "#\t\b\b\b\b89    START MODULOPHPPDV Service"
echo -e "#\t\b\b\b\b88    STOP MODULOPHPPDV Service"
echo -e ""
echo -e "#\t\b\b\b\b79    ATUALIZA_BIBLIOTECA"
echo -e "#\t\b\b\b\b78    AJUSTA TIMEZONE"
echo -e "#\t\b\b\b\b77    WGet Bibliotecas FTP > Path_comum"
echo -e ""
echo -e "#\t\b\b\b\b59    SAT_LAB.CONF BEMATEC"
echo -e "#\t\b\b\b\b58    SAT_LAB.CONF DIMEP"
echo -e "#\t\b\b\b\b57    SAT_LAB.CONF ELGIN"
echo -e "#\t\b\b\b\b56    SAT_LAB.CONF GERTEC"
echo -e "#\t\b\b\b\b55    SAT_LAB.CONF KRYPTUS"
echo -e "#\t\b\b\b\b54    SAT_LAB.CONF MFE_TANCA"
echo -e "#\t\b\b\b\b53    SAT_LAB.CONF NITERE"
echo -e "#\t\b\b\b\b52    SAT_LAB.CONF SWEDA"
echo -e "#\t\b\b\b\b51    SAT_LAB.CONF TANCA"
echo -e "#\t\b\b\b\b50    SAT_LAB.CONF URANO"
echo -e ""
echo -e "#\t\b\b\b\b01    ATUALIZACAO VEIANEWPDV"
echo -e "#\t\b\b\b\b00    SAIR"
echo -e "#\t\b\b\b\b                                                                                 \033[1;47;30m$VERSION\033[0;0m"

echo -ne "#\033[1;32m   INFORME A OPÇÃO DESEJADA: "
read -p "" opt
echo -e "\033[0;0m"
eval "$CASE"

else
clear
echo -e "#\n#\n#\t NAO HA PACOTES DO MODULOPHPPDV DISPONIVEIS PARA EXTRACAO\n#\n#"
sleep 2
clear
fi
}

ListaArquivos
